cleanup:
    - name: Rubble Removal
      length: 540'
      height: 5'
      thickness: 20'
      material: rubble
      material_quality: cheap
      labor:
        building_laborer: 100
      cleanup: true
walls:
    - name: Walls
      length: 540'
      height: 10'
      thickness: 1'
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
      cleanup: false
buildings:
    - name: Northeast Corner Tower
      length: 20'
      width: 20'
      height: 20'
      wall_thickness: 1'
      partition_factor: 0.25
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Northwest Corner Tower
      length: 20'
      width: 20'
      height: 20'
      wall_thickness: 1'
      partition_factor: 0.25
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Southeast Corner Tower
      length: 20'
      width: 20'
      height: 20'
      wall_thickness: 1'
      partition_factor: 0.25
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Southwest Corner Tower
      length: 20'
      width: 20'
      height: 20'
      wall_thickness: 1'
      partition_factor: 0.25
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Gatehouse
      length: 20'
      width: 20'
      height: 20'
      wall_thickness: 1'
      partition_factor: 0.3
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Stables
      length: 60'
      width: 20'
      height: 15'
      wall_thickness: 6"
      partition_factor: 0.3
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Barracks
      length: 60'
      width: 25'
      height: 10'
      wall_thickness: 6"
      partition_factor: 0.25
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
    - name: Officer's Quarters
      length: 50'
      width: 30'
      height: 10'
      wall_thickness: 6"
      partition_factor: 0.5
      material: wood
      material_quality: normal
      labor:
        architect: 1
        building_laborer: 20
        carpenter: 30
        master_carpenter: 3
